Before installing Grails 3.0 you will need as a minimum a Java Development Kit (JDK) installed version 1.7 or above. Download the appropriate JDK for your operating system, run the installer, and then set up an environment variable called `JAVA_HOME` pointing to the location of this installation. 

To automate the installation of Grails we recommend http://sdkman.io[SDKMAN] which greatly simplifies installing and managing multiple Grails versions.

For manual installation, we recommend the video installation guides from http://www.grailsexample.net/[grailsexample.net]:

* http://www.grailsexample.net/installing-a-grails-development-environment-on-windows/[Windows]
* http://www.grailsexample.net/installing-a-grails-development-environment-on-linux/[Linux]
* http://www.grailsexample.net/installing-a-grails-development-environment-on-os-x/[Mac OS X]

These will show you how to install Grails too, not just the JDK.

NOTE: A JDK is required in your Grails development environment. A JRE is not sufficient.

On some platforms (for example OS X) the Java installation is automatically detected. However in many cases you will want to manually configure the location of Java. For example:

[source,groovy]
----
export JAVA_HOME=/Library/Java/Home
export PATH="$PATH:$JAVA_HOME/bin"
---- 

if you're using bash or another variant of the Bourne Shell.
