Before installing Grails 3.0 you will need as a minimum a Java Development Kit (JDK) installed version 1.7 or above. Download the appropriate JDK for your operating system, run the installer, and then set up an environment variable called `JAVA_HOME` pointing to the location of this installation.

To automate the installation of Grails we recommend http://sdkman.io[SDKMAN] which greatly simplifies installing and managing multiple Grails versions.

For manual installation download the zip distrubtion and unzip it to a convenient location and then set the `GRAILS_HOME` environment variable to the location of that installation.

NOTE: A JDK is required in your Grails development environment. A JRE is not sufficient.

The following example shows these steps in action on a Unix system:

[source,bash]
----
$ curl -O https://github.com/grails/grails-core/releases/download/v3.1.12/grails-3.1.12.zip
$ unzip grails-3.1.12.zip -d ~/grails-home
$ export GRAILS_HOME=~/grails-home
$ export PATH="$PATH:$GRAILS_HOME/bin"
----

TIP: On Windows you would have to configure these environment variables in the Advanced section of "My Computer".

On some platforms (for example OS X) the Java installation is automatically detected. However in many cases you will want to manually configure the location of Java. For example:

[source,groovy]
----
export JAVA_HOME=/Library/Java/Home
export PATH="$PATH:$JAVA_HOME/bin"
----

if you're using bash or another variant of the Bourne Shell.
