Before installing Grails 3 you will need as a minimum a Java Development Kit (JDK) installed version 1.7 or 1.8. 

If you want to use JDK 1.7, you need to run Gradle with Java 1.7.0_131-b31 or above to https://blog.gradle.org/unable-to-download-maven-central-bintray[fix Gradle dependency resolution when TLS v1.1 and v1.0 support is discontinued].

Download the appropriate JDK for your operating system, run the installer, and then set up an environment variable called `JAVA_HOME` pointing to the location of this installation.

To automate the installation of Grails we recommend http://sdkman.io[SDKMAN] which greatly simplifies installing and managing multiple Grails versions.

On some platforms (for example OS X) the Java installation is automatically detected. However in many cases you will want to manually configure the location of Java. For example, if you're using bash or another variant of the Bourne Shell:

[source,bash]
----
export JAVA_HOME=/Library/Java/Home
export PATH="$PATH:$JAVA_HOME/bin"
----

TIP: On Windows you would have to configure these environment variables in `My Computer/Advanced/Environment Variables`
