Calling Grails REST services - as well as third-party services - is very straightforward using the https://docs.micronaut.io/latest/guide/index.html#httpClient[Micronaut HTTP Client]. This HTTP client has both a low-level API and a higher level AOP-driven API, making it useful for both simple requests as well as building declarative, type-safe API layers.

To use the Micronaut HTTP client you must have the `micronaut-http-client` dependency on your classpath. Add the following dependency to your `build.gradle` file.

.build.gradle
[source,groovy]
----
compile 'io.micronaut:micronaut-http-client'
----

==== Low-level API

The https://docs.micronaut.io/latest/api/io/micronaut/http/client/HttpClient.html[HttpClient] interface forms the basis for the low-level API. This interfaces declares methods to help ease executing HTTP requests and receive responses.

The majority of the methods in the HttpClient interface returns Reactive Streams Publisher instances, which is not always the most useful interface to work against, hence a sub-interface called RxHttpClient is included that provides a variation of the HttpClient interface that returns RxJava Flowable types.

==== Obtaining a HttpClient

There are a few ways by which you can obtain a reference to a https://docs.micronaut.io/latest/api/io/micronaut/http/client/HttpClient.html[HttpClient]. The most common way is using the https://docs.micronaut.io/latest/api/io/micronaut/http/client/annotation/Client.html[@Client] annotation. For example:

.Injecting an HTTP client
[source, groovy]
----
@Client("https://api.twitter.com/1.1") @Inject RxHttpClient client
----

The https://docs.micronaut.io/latest/api/io/micronaut/http/client/annotation/Client.html[@Client] annotation is also a custom scope that will manage the creation of https://docs.micronaut.io/latest/api/io/micronaut/http/client/HttpClient.html[HttpClient] instances and ensure they are shutdown when the application shuts down.

The value you pass to the https://docs.micronaut.io/latest/api/io/micronaut/http/client/annotation/Client.html[@Client] annotation can be one of the following:

* A absolute URI. Example `https://api.twitter.com/1.1`
* A relative URI, in which case the server targeted will be the current server (useful for testing)
* A service identifier. See the section on *Service Discovery (TODO)* for more information on this topic.

==== Performing an HTTP GET

Generally there are two methods of interest when working with the `HttpClient`. The first method is called `retrieve`, which will execute an HTTP request and return the body in whichever type you request (by default a `String`) as an RxJava rx:Flowable[].

The `retrieve` method accepts an https://docs.micronaut.io/latest/api/io/micronaut/http/HttpRequest.html[HttpRequest] object or a `String` URI to the endpoint you wish to request.

The following example shows how to use `retrieve` to execute an HTTP `GET` and receive the response body (which in this case is a `String`):

.Using retrieve
[source,groovy]
----
given:
String result = client.toBlocking().retrieve("/hello/John")

expect:
result == "Hello John"
----

Note that in this example we are calling `toBlocking()` to return a blocking version of the client.


==== Debugging / Tracing the HTTP Client

To debug the requests being sent and received from the HTTP client you can enable tracing logging via your `logback.groovy` file:

.logback.groovy
[source,groovy]
----
logger("io.micronaut.http.client", TRACE)
----

==== Client Specific Debugging / Tracing

To enable client-specific logging you could configure the default logger for all HTTP clients. And, you could also configure different loggers for different clients using <<_client_specific_configuration, Client Specific Configuration>>. For example, in `application.yml`:

.application.yml
[source,xml]
----
micronaut:
    http:
        client:
            logger-name: mylogger
        services:
            otherClient:
                logger-name: other.client
----

And, then enable logging in `logback.groovy`:

.logback.groovy
[source,groovy]
----
logger("mylogger", DEBUG)
logger("other.client", TRACE)

----

==== Customizing the HTTP Request

The previous example demonstrated using the static methods of the https://docs.micronaut.io/latest/api/io/micronaut/http/HttpRequest.html[HttpRequest] interface to construct a api:http.MutableHttpRequest[] instance. Like the name suggests a `MutableHttpRequest` can be mutated including the ability to add headers, customize the request body and so on. For example:

.Passing an HttpRequest to retrieve
[source,java]
----
include::{testsclient}/basics/HelloControllerTest.java[tags=headers, indent=0]
----

The above example adds an additional header called `X-My-Header` to the request before it is sent. The api:http.MutableHttpRequest[] interface has a bunch more convenience methods that make it easy to modify the request in common ways.


==== Reading JSON Responses

Typically with Microservices a message encoding format is used such as JSON. Micronaut's HTTP client leverages Jackson for JSON parsing hence whatever type Jackson can decode can passed as a second argument to `retrieve`.

For example consider the following controller action that returns a JSON response:

.Returning JSON from a controller
[source,groovy]
----
Message greet() {
    respond(new Message("Hello " + params.name))
}
----

The method above returns a POGO of type `Message` which looks like:

.Message POGO
[source,groovy]
----
class Message {

    String text
}
----

On the client end, you can call this endpoint and decode the JSON into a map using the `retrieve` method as follows:

.Decoding the response body to a Map
[source,groovy]
----
Map response = client.toBlocking().retrieve(GET("/greet/John"), Map)
----

The above examples decodes the response into a `java.util.Map`, representing the JSON. If you wish to customize the type of the key and string you can use the `Argument.of(..)` method:

.Decoding the response body to a Map
[source,groovy]
----
response = client.toBlocking().retrieve(
        GET("/greet/John"),
        Argument.of(Map, String, String)
)
----

<1> The `Argument.of` method is used to return a `Map` whether the key and value are typed as `String`


Whilst retrieving JSON as a map can be desirable, more often than not you will want to decode objects into Plain Old Java Objects (POJOs). To do that simply pass the type instead:

.Decoding the response body to a POJO
[source,groovy]
----
Message response = client.toBlocking().retrieve(
        GET("/greet/John"), Message
)

expect:
response.text == "Hello John"
----

Note how you can use the same Java type on both the client and the server. The implication of this is that typically you will want to define a common API project where you define the interfaces and types that define your API.

==== Decoding Other Content Types

If the server you are communicating with uses a custom content type that is not JSON by default Micronaut's HTTP client will not know how to decode this type.

To resolve this issue you can register api:http.codec.MediaTypeCodec[] as a bean and it will be automatically picked up and used to decode (or encode) messages.

==== Receiving the Full HTTP Response

Sometimes, receiving just the object is not enough and you need information about the response. In this case, instead of `retrieve` you should use the `exchange` method:

.Recieving the Full HTTP Response
[source,groovy]
----
HttpResponse<Message> response = client.toBlocking().exchange(
        GET("/greet/John"), Message
)

Optional<Message> message = response.getBody(Message)

expect:
response.status == HttpStatus.OK

// check the body
message.isPresent()

message.get().text() == "Hello John"
----

<1> The `exchange` method is used to receive the https://docs.micronaut.io/latest/api/io/micronaut/http/HttpResponse.html[HttpResponse]
<2> The body can be retrieved using the `getBody(..)` method of the response
<3> Other aspects of the response, such as the https://docs.micronaut.io/latest/api/io/micronaut/http/HttpStatus.html[HttpStatus] can be checked

The above example receives the full https://docs.micronaut.io/latest/api/io/micronaut/http/HttpResponse.html[HttpResponse] object from which you can obtain headers and other useful information.


