
==== Groovy 2.4


Grails 3.0 comes with Groovy 2.4 which includes many new features and enhancements.

For more information on Groovy 2.4, see the http://groovy-lang.org/releasenotes/groovy-2.4.html[release notes] for more information.


==== Spring 4.1 and Spring Boot 1.2


Grails 3.0 comes with Spring 4.1 which includes many new features and enhancement.

In addition, Grails 3.0 is built on http://projects.spring.io/spring-boot/[Spring Boot 1.2] which provides the ability to produce runnable JAR files that can embed Tomcat, Jetty or Undertow containers.


==== Gradle Build System


Grails 3.0 deprecates the older Gant-based build system in favour of a new http://gradle.org[Gradle-based] build that integrates closely with the http://plugins.gradle.org[Gradle plugin ecosystem].

See the new section on the new link:commandLine.html#gradleBuild[Gradle build] for more information.


==== Application Profiles


Grails 3.0 supports the notion of application profiles via a new http://bintray.com/grails/profiles[profile repository]. A profile encapsulates an application structure, set of commands, plugins and capabilities. For example the "web" profile allows construction of web applications deployable to a Servlet container. In the future more profiles will be developed targeting different environments.

See the new section on link:profiles.html[profiles] for more information.


==== Redesigned API based on Traits


The Grails API has been redesigned so that public API is correctly populated under the `grails.` package whilst private / internal API that is subject to change can be found in the `org.grails.` package. The core API has also been rewritten and based around the http://groovy-lang.org/objectorientation.html#_traits[Groovy Traits].

See the new documentation on Grails 3.0's link:traits.html[core traits] for more information.
