
==== New default date data binding format


Dates formatted like "1970-01-01T00:00:00.000Z" will now be successfully parsed by default. The format is used by common JavaScript libraries.


==== The `run-script` command from Grails 2 is back


The `run-script` command makes a return! It is now possible to run Groovy scripts that are wrapped in a Grails context using Grails 3:

[source,groovy]
----
$ grails run-script my-groovy-script.groovy
----

Refer to the link:../ref/Command%20Line/run-script.html[run-script] documentation for more information.


==== Commands, a feature previously only available in plugins, are now available to be created in applications


[source,groovy]
----
$ grails create-command MyCommand
----

Note that commands defined in applications are not executed the same way by default. See the updated documentation on link:../ref/Command%20Line/create-command.html[create-command] for details.


==== REST Profile Refinements


The REST profile has been further refined including more sensible `UrlMappings` and mime type configuration designed specifically for REST applications.


==== Ability to skip the Bootstrap process with a system property


When the Grails runtime is started, it will now execute `*Bootstrap.groovy` classes conditionally. If the system property `grails.bootstrap.skip` is set to `true`, the classes will _not_ be executed for that run.


==== Changes to data binding with the body of a request


To be more inline with the https://tools.ietf.org/html/rfc2616#section-4.3[HTTP/1.1] specification, request bodies in GET and DELETE requests will be ignored for data binding. The request body will also be ignored if the specified content length is 0.


==== Profile improvements


It is now possible to specify credentials for repositories used for profile resolution in your `settings.groovy` file. In addition, there are other new features useful for creating profiles. See the link:profiles.html[section on Profiles] for the documentation.
