Within the `<% %>` brackets you can declare variables:

[source,xml]
----
<% now = new Date() %>
----

and then access those variables later in the page:

[source,xml]
----
<%=now%>
----

Within the scope of a GSP there are a number of pre-defined variables, including:

* `application` - The {javaee}javax/servlet/ServletContext.html[ServletContext] instance
* `applicationContext` The Spring {springapi}org/springframework/context/ApplicationContext.html[ApplicationContext] instance
* `flash` - The link:../ref/Controllers/flash.html[flash] object
* `grailsApplication` - The {apiDocs}grails/core/GrailsApplication.html[GrailsApplication] instance
* `out` - The response writer for writing to the output stream
* `params` - The link:../ref/Controllers/params.html[params] object for retrieving request parameters
* `request` - The {javaee}javax/servlet/http/HttpServletRequest.html[HttpServletRequest] instance
* `response` - The {javaee}javax/servlet/http/HttpServletResponse.html[HttpServletResponse] instance
* `session` - {javaee}javax/servlet/http/HttpSession.html[HttpSession] instance
* `webRequest` - The {apiDocs}org/grails/web/servlet/mvc/GrailsWebRequest.html[GrailsWebRequest] instance
