
===== findOrSaveBy*



===== Purpose


Dynamic method that uses the properties of the domain class to create query method expressions that return the first result of the query. This method behaves like <<ref-domain-classes-findBy,findBy>> except that it will never return `null`.  If a matching instance cannot be found then a new instance will be created, populated with values represented in the query parameters, saved and returned. The difference between this method and <<ref-domain-classes-findOrCreateBy,findOrCreateBy>> is that this method will save any newly created instance where <<ref-domain-classes-findOrCreateBy,findOrCreateBy>> does not.


===== Examples


Given the domain class `Book`:

[source,java]
----
class Book {
   String title
   String author
}
----

The following are all possible:

[source,java]
----
def b = Book.findOrSaveByTitleAndAuthor("The Sum of All Fears", "Tom Clancy")
----

The following are roughly equivalent:

[source,java]
----
def b = Book.findOrSaveByTitleAndAuthor("The Sum of All Fears", "Tom Clancy")
----

[source,java]
----
def b = Book.findByTitleAndAuthor("The Sum of All Fears", "Tom Clancy")
if (!b) {
    b = new Book(title: "The Sum of All Fears", author: "Tom Clancy")
    b.save()
}
----


===== Description


GORM supports the notion of <<finders,Dynamic Finders>>. The `findOrSaveBy*` method finds the first result for the given method expression.

NOTE: Because this method potentially creates a new instance and populates properties on that instance, only exact match criteria are allowed.  For example, `Book.findOrSaveByTitle(authorValue)` is valid but `Book.findOrSaveByAuthorInList(listOfNames)` is not.
