Grails 3.3 includes several changes to dependencies and Event publishing that may require changes to your application if you are upgrading from Grails 3.2.x.

TIP: For information on upgrading from versions of Grails prior to Grails 3.2.x, see the http://docs.grails.org/3.2.x/guide/upgrading.html[Grails 3.2.x documentation on upgrading]

=== GORM 6.1 Upgrade

GORM 6.1 http://gorm.grails.org/latest/hibernate/manual/index.html#upgradeNotes[includes changes] that may require you to change your application.

==== GORM Async Now Optional

Notably `grails-datastore-gorm-async` is now optional and if you use the `task` method of GORM you will need to manually implement the `AsyncEntity` trait.

==== Domain Autowiring Disabled

Domain class autowiring is disabled by default due to its impact on performance. You can re-enable autowiring using the `grails.gorm.autowire` setting in `application.yml`.

==== Flush Mode now COMMIT by Default

The default flush mode has been change to `COMMIT` due to the impact the previous flush mode `AUTO` has on read performance. You can switch back to `AUTO` use the `hibernate.flush.mode` setting in `application.yml`

==== Tomcat JDBC

GORM 6.1 and above now supports multiple connection pool options, so the `tomcat-jdbc` dependency is now optional. If you are upgrading you may need to add it (or another pool implementation) to your `build.gradle`:

[source,groovy]
.build.gradle
----
runtime 'org.apache.tomcat:tomcat-jdbc'
----

=== Dependency Alterations

In an effort to trim the size of the produced WAR file by Grails several dependencies are no longer resolved transtively including:

* `commons-lang`
* `gson`
* `aspectjweaver`
* `aspectjrt`
* `ehcache`

If you are upgrading and have referenced any of these dependencies in your application you may need to alter your build to reference them.

=== Spring Boot 1.5.x

Spring Boot 1.5.x removes a number of deprecated classes, notably all of the classes within the `org.springframework.boot.context.embedded` package.

If your application is referencing any of the classes within this package you will need to alter your imports to use `org.springframework.boot.web.servlet` instead.

=== Reactor 2.x Deprecated and Removed

Since Reactor 2.x is no longer being maintained and a new ink:{asyncdocs}[EventBus] abstraction has been implemented, Reactor 2.x and all its dependencies have been removed.

A compatibility layer has been provided to allow classes compiled with the previous version that uses Reactor to run, however all plugins and application code should be re-compiled and direct references to Reactor 2.x should be removed.

=== Externalized Plugins

Several plugins and libraries have been separated from Grails core into standalone projects. The following table summarizes the previous artefact id, the new artefact id and the location of the new sources:

.Externalized Plugins
|===
|Previous Artefact ID |New Artefact ID |Sources

|`org.grails:grails-plugin-gsp`
|`org.grails.plugins:gsp`
|https://github.com/grails/grails-gsp

|`org.grails:grails-plugin-converters`
|`org.grails.plugins:converters`
|https://github.com/grails-plugins/grails-plugin-converters

|`org.grails:grails-plugin-async`
|`org.grails.plugins:async`
|https://github.com/grails/grails-async

|`org.grails:grails-plugin-events`
|`org.grails.plugins:events`
|https://github.com/grails/grails-events

|===
