When you create a new project with the link:../ref/Command%20Line/create-app.html[create-app] command, a default `build.gradle` is created. The default `build.gradle` configures the build with a set of Gradle plugins that allow Gradle to build the Grails project:

[source,groovy]
----
apply plugin:"war"
apply plugin:"org.grails.grails-web"
apply plugin:"org.grails.grails-gsp"
apply plugin:"asset-pipeline"
----

The default plugins are as follows:

* `war` - The http://www.gradle.org/docs/current/userguide/war_plugin.html[WAR plugin] changes the packaging so that Gradle creates as WAR file from your application. You can comment out this plugin if you wish to create only a runnable JAR file for standalone deployment.
* `asset-pipeline` - The https://grails.org/plugins.html#plugin/asset-pipeline[asset pipeline] plugin enables the compilation of static assets (JavaScript, CSS etc.)


Many of these are built in plugins provided by Gradle or third party plugins. The Gradle plugins that Grails provides are as follows:

* `org.grails.grails-core` - The primary Grails plugin for Gradle, included by all other plugins and designed to operate with all profiles.
* `org.grails.grails-gsp` - The Grails GSP plugin adds precompilation of GSP files for production deployments.
* `org.grails.grails-doc` - A plugin for Gradle for using Grails 2.0's documentation engine.
* `org.grails.grails-plugin` - A plugin for Gradle for building Grails plugins.
* `org.grails.grails-plugin-publish` - A plugin for publishing Grails plugins to the central repository.
* `org.grails.grails-profile` - A plugin for use when creating Grails <<profiles,Profiles>>.
* `org.grails.grails-profile-publish` - A plugin for publishing Grails profiles to the central repository.
* `org.grails.grails-web` - The Grails Web gradle plugin configures Gradle to understand the Grails conventions and directory structure.



