### Bump up Grails Version

You will need to upgrade your Grails version defined in `gradle.properties` as:

[source,groovy,subs="attributes"]
.gradle.properties
----
...
grailsVersion=6.0.0
...
----

### Bump up GORM Version

If you were using http://gorm.grails.org[GORM], you will need to update the version defined in `gradle.properties` as:

[source, properties]
.gradle.properties
----
...
gormVersion=8.0.0
...
----

### Bump up gradle version

Grails 6 uses Gradle 7.6.2

[source, properties]
.gradle-wrapper.properties
----
...
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.2-bin.zip
...
----

Also you can run this command

[source, properties]
----
./gradlew wrapper --gradle-version 7.6.2
----

### GORM for MonogDB Sync Driver

The GORM for MongoDB is updated to support latest mongodb-driver-sync. If you are using GORM for MongoDB and doing something specific to MongoDB Driver or low level Mongo API then you might want to take a look at https://mongodb.github.io/mongo-java-driver/4.0/upgrading/[Upgrading to the 4.0 Driver]

### Bump up Asset Pipeline plugin version

The previous version of asset-pipeline is not supported with Grails 5.0 as it is compiled with a version of Groovy which is binary incompatible with Groovy 3. So, please update the plugin version to 3.4.7.

### Spring 5.3

Grails 6 is built on Spring 5.3.26 See the https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#upgrading-to-version-53[Upgrading to Spring 5.3]  if you are using Spring specific features.

### Spring Boot 2.7

Grails 6 updates to Spring Boot 2.7. Please check https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes[Spring Boot 2.7 Release Notes] for more information.

### Micronaut 3.9.3

Grails 6 is shipped with Micronaut 3.9.3. Please check the https://docs.micronaut.io/3.9.3/guide/index.html#upgrading[Upgrading to Micronaut 3.x] if you are using a specific feature.

### Micronaut for Spring 4.5.1

Grails 6 is updated to Micronaut for Spring 4.5.1, please check out https://github.com/micronaut-projects/micronaut-spring/releases/tag/v4.5.1[release notes] for more information.

### Gradle 7.x

The Grails 6 is updated to Gradle 7.6.2, we recommend checking the https://docs.gradle.org/7.6.2/release-notes.html[Official Gradle Release Notes] for more information.
