
==== Form Basics


GSP supports many different tags for working with HTML forms and fields, the most basic of which is the link:../ref/Tags/form.html[form] tag. This is a controller/action aware version of the regular HTML form tag. The `url` attribute lets you specify which controller and action to map to:

[source,xml]
----
<g:form name="myForm" url="[controller:'book',action:'list']">...</g:form>
----

In this case we create a form called `myForm` that submits to the `BookController`'s `list` action. Beyond that all of the usual HTML attributes apply.


==== Form Fields


In addition to easy construction of forms, GSP supports custom tags for dealing with different types of fields, including:

* link:../ref/Tags/textField.html[textField] - For input fields of type 'text'
* link:../ref/Tags/passwordField.html[passwordField] - For input fields of type 'password'
* link:../ref/Tags/checkBox.html[checkBox] - For input fields of type 'checkbox'
* link:../ref/Tags/radio.html[radio] - For input fields of type 'radio'
* link:../ref/Tags/hiddenField.html[hiddenField] - For input fields of type 'hidden'
* link:../ref/Tags/select.html[select] - For dealing with HTML select boxes

Each of these allows GSP expressions for the value:

[source,xml]
----
<g:textField name="myField" value="${myValue}" />
----

GSP also contains extended helper versions of the above tags such as link:../ref/Tags/radioGroup.html[radioGroup] (for creating groups of link:../ref/Tags/radio.html[radio] tags), link:../ref/Tags/localeSelect.html[localeSelect], link:../ref/Tags/currencySelect.html[currencySelect] and link:../ref/Tags/timeZoneSelect.html[timeZoneSelect] (for selecting locales, currencies and time zones respectively).


==== Multiple Submit Buttons


The age old problem of dealing with multiple submit buttons is also handled elegantly with Grails using the link:../ref/Tags/actionSubmit.html[actionSubmit] tag. It is just like a regular submit, but lets you specify an alternative action to submit to:

[source,xml]
----
<g:actionSubmit value="Some update label" action="update" />
----
