
==== Validation Basics


Call the <<ref-domain-classes-validate,validate>> method to validate a domain class instance:

[source,java]
----
def user = new User(params)

if (user.validate()) {
    // do something with user
}
else {
    user.errors.allErrors.each {
        println it
    }
}
----

The `errors` property on domain classes is an instance of the Spring http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/validation/Errors.html[Errors] interface. The `Errors` interface provides methods to navigate the validation errors and also retrieve the original values.


==== Validation Phases


Within Grails there are two phases of validation, the first one being <<dataBinding,data binding>> which occurs when you bind request parameters onto an instance such as:

[source,java]
----
def user = new User(params)
----

At this point you may already have errors in the `errors` property due to type conversion (such as converting Strings to Dates). You can check these and obtain the original input value using the `Errors` API:

[source,java]
----
if (user.hasErrors()) {
    if (user.errors.hasFieldErrors("login")) {
        println user.errors.getFieldError("login").rejectedValue
    }
}
----

The second phase of validation happens when you call <<ref-domain-classes-validate,validate>> or <<ref-domain-classes-save,save>>. This is when Grails will validate the bound values against the <<ref-domain-classes-constraints,constraints>> you defined. For example, by default the <<ref-domain-classes-save,save>> method calls `validate` before executing, allowing you to write code like:

[source,java]
----
if (user.save()) {
    return user
}
else {
    user.errors.allErrors.each {
        println it
    }
}
----
