
===== formatDate



===== Purpose


Formats `java.util.Date` instances using the patterns defined by the https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html[SimpleDateFormat] class.


===== Examples


[source,xml]
----
<g:formatDate format="yyyy-MM-dd" date="${date}"/>
----

[source,xml]
----
<g:formatDate date="${date}" type="datetime" style="MEDIUM"/>
----

[source,xml]
----
<g:formatDate date="${date}" type="datetime" style="LONG" timeStyle="SHORT"/>
----

[source,xml]
----
<g:formatDate date="${date}" type="time" style="SHORT"/>
----


===== Description


Attributes

* `date` (required) - The date object to format
* `format` (optional) - The formatting pattern to use for the date, see https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html[SimpleDateFormat]
* `formatName` (optional) - Look up `format` from the default MessageSource / ResourceBundle (i18n/*.properties file) with this key. If `format` and `formatName` are empty, `format` is looked up with '`default.date.format`' key. Defaults to 'yyyy-MM-dd HH:mm:ss z' if the key not specified
* `type` (optional) - The type of format to use for the date / time. `format` or `formatName` aren't used when `type` is specified. Possible values: 'date' - shows only date part, 'time' - shows only time part, 'both'/'datetime' - shows date and time
* `timeZone` (optional) - Sets the time zone for formatting. See https://docs.oracle.com/javase/8/docs/api/java/util/TimeZone.html[TimeZone] class.
* `locale` (optional) - Force the locale for formatting.
* `style` (optional) - Use default date/time formatting of the country specified by the locale. Possible values: SHORT (default), MEDIUM, LONG, FULL . See https://docs.oracle.com/javase/8/docs/api/java/text/DateFormat.html[DateFormat] for explanation.
* `dateStyle` (optional) - Set separate `style` for the date part.
* `timeStyle` (optional) - Set separate `style` for the time part.


===== Source


{source:tag=FormatTagLib.formatDate}
{source}
