GORM classes also support Hibernate's query language HQL, a very complete reference for which can be found http://docs.jboss.org/hibernate/core/3.6/reference/en-US/html/queryhql.html[in the Hibernate documentation] of the Hibernate documentation.

GORM provides a number of methods that work with HQL including link:../ref/Domain%20Classes/find.html[find], link:../ref/Domain%20Classes/findAll.html[findAll] and link:../ref/Domain%20Classes/executeQuery.html[executeQuery]. An example of a query can be seen below:

[source,groovy]
----
def results =
      Book.findAll("from Book as b where b.title like 'Lord of the%'")
----


==== Positional and Named Parameters


In this case the value passed to the query is hard coded, however you can equally use positional parameters:

[source,groovy]
----
def results =
      Book.findAll("from Book as b where b.title like ?", ["The Shi%"])
----

[source,groovy]
----
def author = Author.findByName("Stephen King")
def books = Book.findAll("from Book as book where book.author = ?",
                         <<author>>)
----

Or even named parameters:

[source,groovy]
----
def results =
      Book.findAll("from Book as b " +
                   "where b.title like :search or b.author like :search",
                   [search: "The Shi%"])
----

[source,groovy]
----
def author = Author.findByName("Stephen King")
def books = Book.findAll("from Book as book where book.author = :author",
                         [author: author])
----


==== Multiline Queries


-NOTE: -As of Grails 3.0.3, Triple-quoted Groovy multiline Strings now work properly with HQL queries.
-

Use the line continuation character to separate the query across multiple lines:

[source,groovy]
----
def results = Book.findAll("\\\
from Book as b, \\\
     Author as a \\\
where b.author = a and a.surname = ?", ['Smith'])
----

or

[source,groovy]
----
def results = Book.findAll("""
from Book as b,
     Author as a
where b.author = a and a.surname = ?", ['Smith']
""")
----


==== Pagination and Sorting


You can also perform pagination and sorting whilst using HQL queries. To do so simply specify the pagination options as a Map at the end of the method call and include an "ORDER BY" clause in the HQL:

[source,groovy]
----
def results =
      Book.findAll("from Book as b where " +
                   "b.title like 'Lord of the%' " +
                   "order by b.title asc",
                   [max: 10, offset: 20])
----
