== `create-app`

=== Purpose

The `create-app` command serves as the initial step in Grails application development. When invoked, this command generates a Grails application with a user-specified name. Subsequently, it creates a subdirectory based on the provided application name within the directory where the command is executed.

=== Examples

To illustrate its usage, here are some examples:

1. Create an application within a directory named "bookstore":
+
[source,bash]
----
$ grails create-app bookstore
$ cd bookstore
----

2. Create an application directly in the current directory:
+
[source,bash]
----
$ mkdir bookstore
$ cd bookstore
$ grails create-app --inplace
----

3. Customize the application by adding specific features (available since Grails 3.1):
+
[source,bash]
----
$ grails create-app bookstore --features github-workflow-java-ci,asciidoctor
----

Arguments:

- `NAME`: The desired name for the application.
- `-f, --features=FEATURE[,FEATURE...]`: Specifies the features to include. Available options include h2, scaffolding, gorm-hibernate5, spring-boot-starter-jetty, springloaded, spring-boot-starter-tomcat, micronaut-http-client, cache-ehcache, hibernate-validator, postgres, mysql, cache, database-migration, grails-gsp, hamcrest, gorm-mongodb, assertj, mockito, spring-boot-starter-undertow, micronaut-inject-groovy, github-workflow-java-ci, jrebel, testcontainers, sqlserver, grails-console, views-markup, asset-pipeline-grails, views-json, gorm-neo4j, asciidoctor, embedded-mongodb, grails-web-console, logbackGroovy, mongo-sync, shade, geb, properties.
- `-g, --gorm=GORM Implementation`: Specifies the GORM Implementation to configure, with options like hibernate, mongodb, neo4j.
- `-h, --help`: Displays the help message and exits.
- `-i, --inplace`: Creates a service within the current directory.
- `--jdk=<javaVersion>`: Specifies the JDK version for the project.
- `--list-features`: Outputs available features and their descriptions.
- `-s, --servlet=Servlet Implementation`: Specifies the Servlet Implementation, with choices including none, tomcat, jetty, undertow.
- `-t, --test=TEST`: Specifies the test framework, with options such as junit, spock.
- `-v, --verbose`: Generates verbose output.
- `-V, --version`: Prints version information and exits.
- `-x, --stacktrace`: Displays a full stack trace in case of exceptions.
