== create-app

=== Purpose

The starting point for Grails. This command creates a Grails application using the name specifed by the user. A subdirectory within the directory the command was executed from is then created based on the specified application name.

=== Examples

Create an application in a directory that matches the application name:

[source,bash]
----
$ grails create-app bookstore
$ cd bookstore
----

Create an application in the current directory:

[source,bash]
----
$ mkdir bookstore
$ cd bookstore
$ grails create-app --inplace
----

Create an application customizing the profile and features (since Grails 3.1):

[source,bash]
----
$ grails create-app bookstore --profile web --features mongodb,asset-pipeline
$ grails create-app bookstore --profile rest-api --features hibernate
----

Arguments:

* `profile` - The profile to use to create the application
* `features` - The features to use when creating the application
* `inplace` - Whether to create the application within the current directory
* `skip-wrapper` - If set the grailsw wrapper script and support files will not be generated


=== Description


The `create-app` command is responsible for creating an application. By default the command will create an application using the "web" profile. For other available profiles use the link:list-profiles.html[list-profiles] and link:../ref/Command%20Line/profile-info.html[profile-info] commands to find out what profiles are available. For more information on profiles see the <<profiles,Profiles>> section of the user guide.

Usage:
[source,java]
----
grails create-app <<name>> [--skip-wrapper] [--profile] <<profile name>> [--features] <<FEATURE NAMES>>
----
