
== schema-export



=== Purpose


Uses Hibernate's SchemaExport tool to generate DDL or export the schema.
NOTE: As of Grails 3, the Hibernate plugin is not by default on the build classpath. You need to add it to the build classpath to get the command working.


=== Examples


[source,java]
----
//Add Hibernate to the build classpath
buildscript {
    dependencies {
        classpath "org.grails.plugins:hibernate:4.3.8.0"
    }
}
----


[source,java]
----
grails schema-export
grails schema-export --datasource=lookup
grails prod schema-export
grails dev schema-export
grails prod schema-export export
grails prod schema-export export --datasource=auditing
grails prod schema-export stdout
----


=== Description


Usage:
[source,java]
----
grails <<environment>> schema-export <<action>> ['stdout'] <<filename>> [--datasource]
----

Arguments:

* `environment` - The environment containing the database configuration to use (dev, prod, etc...).
* `action` - Either 'generate' or 'export'.  The default is 'generate'. Specifying 'export' will execute the script against the specified environment's database instead of just generating the ddl file.
* `stdout` - Passing 'stdout' will cause the script to dump the ddl to stdout.
* `filename` - The name of the file to write the ddl to.  The default is ddl.sql in the project's 'target' directory.
* `datasource` - The `DataSource` name suffix; defaults to the default `DataSource` if not specified

