name: "Java CI"
on:
  push:
    branches:
      - '[4-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[4-9]+.[0-9]+.x'
  workflow_dispatch:
env:
  GIT_USER_NAME: grails-build
  GIT_USER_EMAIL: grails-build@users.noreply.github.com
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout the repository"
        uses: actions/checkout@v4
      - name: "🔀 Store current branch name"
        run: |
          TARGET_BRANCH="${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}"
          echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
          echo "Target Branch: ${TARGET_BRANCH}"
      - name: "📅 Set current date as env variable"
        run: |
          NOW=$(date +'%Y-%m-%dT%H%M%S')
          echo "NOW=${NOW}" >> $GITHUB_ENV
          echo "Current date: ${NOW}"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "🔨 Build Snapshot Documentation"
        run: >
          ./gradlew build
          -PgithubBranch=${{ env.TARGET_BRANCH }}
      - name: "📤 Upload Generated Docs to Workflow Result Page"
        uses: actions/upload-artifact@v4
        with:
          name: grails-docs-${{ env.NOW }}.zip
          path: ./build/distributions/*.zip
          compression-level: 0 # Already a zip
      - name: "📤 Publish Snapshot Documentation to Github Pages"
        if: github.event_name == 'push'
        uses: grails/github-pages-deploy-action@v3
        env:
          BRANCH: gh-pages
          COMMIT_EMAIL: ${{ env.GIT_USER_EMAIL }}
          COMMIT_NAME: ${{ env.GIT_USER_NAME }}
          FOLDER: build/docs
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SKIP_SNAPSHOT: ${{
              startsWith(steps.extract_branch.outputs.value, '3.3') ||
              startsWith(steps.extract_branch.outputs.value, '4.1') ||
              startsWith(steps.extract_branch.outputs.value, '5.3') || 
              startsWith(steps.extract_branch.outputs.value, '6.2')
            }}
